export const DRAWBACK_PROMPTS: string[] = [
  "A dog trying to DJ",
  "Your face when the aux gets taken",
  "A pizza with legs running away",
  "The last thing you Googled",
  "A cat judging you",
  "Someone dancing badly at a party",
  "A phone with feelings",
  "Your brain at 3am",
  "A confused alien at a party",
  "The DJ booth at the end of the night",
  "A fish driving a car",
  "Someone trying to parallel park",
  "A cloud that is also a couch",
  "Your pet pretending to be human",
  "A very confident pigeon",
  "Monday morning energy",
  "Friday night energy",
  "A sandwich having an existential crisis",
  "The WiFi signal as a person",
  "A haunted vending machine",
  "Someone's grandma crowd surfing",
  "A robot trying to make friends",
  "The moon working a 9-5",
  "A bear in a business meeting",
  "Your boss as a potato",
  "A snail in a hurry",
  "Two left feet (literally)",
  "A DJ with no ears",
  "A crowd of one person",
  "The quiet kid at a party",
  "A flamingo at the gym",
  "Spaghetti becoming sentient",
  "A superhero who is afraid of everything",
  "A fortune cookie with bad advice",
  "The world's worst magic trick",
  "A traffic jam on a rollercoaster",
  "A dinosaur taking a selfie",
  "Someone who just remembered something embarrassing",
  "A sock looking for its partner",
  "The last slice of pizza protecting itself",
  "A cactus on a first date",
  "The moon getting a parking ticket",
  "An octopus trying to hug everyone at once",
  "A toaster that thinks it's a DJ",
  "Your anxiety as a physical object",
  "A ghost who is also a food critic",
  "A bored cloud refusing to rain",
  "A dog discovering it has hands",
  "The inside of a microwave at midnight",
  "A chair having a midlife crisis",
  "Two rocks having an argument",
  "A potato running for office",
  "An elevator with a grudge",
  "The sun clocking out early on a Monday",
  "A lamp that is also a detective",
  "A cat explaining the stock market",
  "An ice cube melting dramatically",
  "A crab trying to parallel park",
  "A burrito with trust issues",
  "A clock that has given up",
  "A giraffe stuck in a revolving door",
  "The last battery bar on your phone",
  "A shopping cart with one bad wheel living its best life",
  "A snowman on a beach in denial",
  "A hotdog at a five-star restaurant",
  "An alarm clock with enemies",
  "A sock puppet receiving bad news",
  "An avocado realising it's too ripe",
  "A toilet seat that has seen too much",
  "A broom who thinks it can fly without magic",
  "A houseplant judging everyone in the room",
  "A bench at a bus stop waiting forever",
  "A cloud shaped exactly like its worst fear",
  "A fridge door that just needs to be heard",
  "A sunflower growing in an unexpected location",
  "Two traffic cones gossiping",
  "A stapler who has no more staples and it shows",
  "A candle at 1% wick living on the edge",
  "A mirror that refuses to show your face",
  "A fire alarm that cried wolf one too many times",
];
