export interface GeoLocation {
  id: string;
  name: string;       // Revealed AFTER guessing
  lat: number;
  lng: number;
  hint: string;       // Vague clue shown during guessing (continent / climate)
  imageUrl?: string;  // Real Wikimedia Commons image URL
}

export const GEO_LOCATIONS: GeoLocation[] = [
  // ── Europe ──────────────────────────────────────────────────────────────────
  {
    id: "paris",
    name: "Eiffel Tower, Paris",
    lat: 48.858, lng: 2.295,
    hint: "Western Europe — iron lattice tower dominates the skyline",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/1280px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg",
  },
  {
    id: "rome",
    name: "Colosseum, Rome",
    lat: 41.890, lng: 12.492,
    hint: "Southern Europe — ancient stone amphitheatre",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/1280px-Colosseo_2020.jpg",
  },
  {
    id: "london",
    name: "Big Ben, London",
    lat: 51.501, lng: -0.124,
    hint: "Northern Europe — famous clock tower beside a river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007_icon.png/800px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007_icon.png",
  },
  {
    id: "barcelona",
    name: "Sagrada Família, Barcelona",
    lat: 41.404, lng: 2.174,
    hint: "Southern Europe — unfinished cathedral with organic spires",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sagrada_Familia_nave_roof_detail.jpg/1280px-Sagrada_Familia_nave_roof_detail.jpg",
  },
  {
    id: "athens",
    name: "Acropolis, Athens",
    lat: 37.971, lng: 23.726,
    hint: "Southern Europe — ancient hilltop temple complex",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/1280px-The_Parthenon_in_Athens.jpg",
  },
  {
    id: "amsterdam",
    name: "Canals, Amsterdam",
    lat: 52.374, lng: 4.890,
    hint: "Western Europe — city of historic waterways and narrow houses",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Amsterdam_-_Wikimedia_Commons_%281%29.jpg/1280px-Amsterdam_-_Wikimedia_Commons_%281%29.jpg",
  },
  {
    id: "santorini",
    name: "Santorini, Greece",
    lat: 36.393, lng: 25.461,
    hint: "Mediterranean — white cube buildings on a volcanic caldera",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Santorini_-_panoramio_%283%29.jpg/1280px-Santorini_-_panoramio_%283%29.jpg",
  },
  {
    id: "stonehenge",
    name: "Stonehenge, England",
    lat: 51.179, lng: -1.826,
    hint: "Northwestern Europe — prehistoric stone circle on a grassy plain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/1280px-Stonehenge2007_07_30.jpg",
  },
  {
    id: "budapest",
    name: "Budapest, Hungary",
    lat: 47.498, lng: 19.040,
    hint: "Central Europe — parliament building straddling a great river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Parliament_Budapest_2010.jpg/1280px-Parliament_Budapest_2010.jpg",
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik, Croatia",
    lat: 42.651, lng: 18.094,
    hint: "Adriatic coast — walled medieval city by a turquoise sea",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Dubrovnik_-_Old_City_Walls.jpg/1280px-Dubrovnik_-_Old_City_Walls.jpg",
  },
  {
    id: "amalfi",
    name: "Amalfi Coast, Italy",
    lat: 40.634, lng: 14.603,
    hint: "Southern Italy — colourful cliffside villages above a blue sea",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Costiera_amalfitana.jpg/1280px-Costiera_amalfitana.jpg",
  },

  // ── Americas ─────────────────────────────────────────────────────────────────
  {
    id: "nyc",
    name: "Statue of Liberty, New York",
    lat: 40.689, lng: -74.044,
    hint: "North America — copper lady on an island in a famous harbour",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/24701-nature-natural-beauty.jpg/1280px-24701-nature-natural-beauty.jpg",
  },
  {
    id: "rio",
    name: "Christ the Redeemer, Rio",
    lat: -22.952, lng: -43.210,
    hint: "South America — giant statue with arms wide open on a mountain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg/1280px-Christ_the_Redeemer_-_Cristo_Redentor.jpg",
  },
  {
    id: "machu",
    name: "Machu Picchu, Peru",
    lat: -13.163, lng: -72.545,
    hint: "South America — Inca citadel hidden in the Andes cloud forest",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1280px-Machu_Picchu%2C_Peru.jpg",
  },
  {
    id: "chicago",
    name: "Chicago, USA",
    lat: 41.878, lng: -87.630,
    hint: "North America — windy city with distinctive bean sculpture",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Chicago_lakefront_skyline_c2009-2.jpg/1280px-Chicago_lakefront_skyline_c2009-2.jpg",
  },
  {
    id: "mexico",
    name: "Chichen Itza, Mexico",
    lat: 20.683, lng: -88.569,
    hint: "Central America — stepped Maya pyramid in the jungle",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/1280px-Chichen_Itza_3.jpg",
  },
  {
    id: "patagonia",
    name: "Patagonia, Argentina",
    lat: -51.629, lng: -72.700,
    hint: "Southern South America — dramatic granite towers above glaciers",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Patagonia_-_Argentina_%28cropped%29.jpg/1280px-Patagonia_-_Argentina_%28cropped%29.jpg",
  },
  {
    id: "havana",
    name: "Havana, Cuba",
    lat: 23.135, lng: -82.359,
    hint: "Caribbean — colourful colonial streets with vintage American cars",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Havana-streets2.jpg/1280px-Havana-streets2.jpg",
  },
  {
    id: "grand_canyon",
    name: "Grand Canyon, USA",
    lat: 36.106, lng: -112.113,
    hint: "North America — massive rust-red gorge carved by a river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg/1280px-USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg",
  },
  {
    id: "banff",
    name: "Banff, Canada",
    lat: 51.178, lng: -115.571,
    hint: "North America — turquoise glacial lake framed by Rocky Mountains",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Moraine_Lake_17092005.jpg/1280px-Moraine_Lake_17092005.jpg",
  },
  {
    id: "iguazu",
    name: "Iguazu Falls, Argentina",
    lat: -25.695, lng: -54.437,
    hint: "South America — vast waterfall system wider than Niagara",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Iguazu_Argentina_Luca_Galuzzi_2007_03.jpg/1280px-Iguazu_Argentina_Luca_Galuzzi_2007_03.jpg",
  },
  {
    id: "easter_island",
    name: "Easter Island, Chile",
    lat: -27.112, lng: -109.349,
    hint: "South Pacific — mysterious giant stone heads on a remote island",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Easter_Island_Ahu_Tongariki.jpg/1280px-Easter_Island_Ahu_Tongariki.jpg",
  },

  // ── Asia ─────────────────────────────────────────────────────────────────────
  {
    id: "taj",
    name: "Taj Mahal, India",
    lat: 27.175, lng: 78.042,
    hint: "South Asia — white marble mausoleum reflected in a long pool",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/1280px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg",
  },
  {
    id: "tokyo",
    name: "Tokyo, Japan",
    lat: 35.689, lng: 139.692,
    hint: "East Asia — futuristic megacity with neon-lit crossings",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg",
  },
  {
    id: "china",
    name: "Great Wall, China",
    lat: 40.432, lng: 116.570,
    hint: "East Asia — ancient stone wall winding over mountain ridges",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/1280px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
  },
  {
    id: "dubai",
    name: "Burj Khalifa, Dubai",
    lat: 25.197, lng: 55.274,
    hint: "Middle East — world's tallest skyscraper in a desert city",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Burj_Khalifa.jpg/800px-Burj_Khalifa.jpg",
  },
  {
    id: "angkor",
    name: "Angkor Wat, Cambodia",
    lat: 13.412, lng: 103.867,
    hint: "Southeast Asia — vast Hindu-Buddhist temple complex in the jungle",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Angkor_Wat_temple.jpg/1280px-Angkor_Wat_temple.jpg",
  },
  {
    id: "singapore",
    name: "Marina Bay, Singapore",
    lat: 1.282, lng: 103.861,
    hint: "Southeast Asia — futuristic skyline with a rooftop infinity pool",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Singapura_-_Skyline_nocturno_%28by_Drriss_%26_Marrionn%29.jpg/1280px-Singapura_-_Skyline_nocturno_%28by_Drriss_%26_Marrionn%29.jpg",
  },
  {
    id: "kyoto",
    name: "Fushimi Inari, Kyoto",
    lat: 34.967, lng: 135.773,
    hint: "East Asia — thousands of bright orange torii gates up a forested hill",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Fushimi_inari_taisha_1.jpg/1280px-Fushimi_inari_taisha_1.jpg",
  },
  {
    id: "bali",
    name: "Bali, Indonesia",
    lat: -8.340, lng: 115.092,
    hint: "Southeast Asia — terraced rice paddies and ornate Hindu temples",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Bali_Indonesia_%28241279698%29.jpg/1280px-Bali_Indonesia_%28241279698%29.jpg",
  },
  {
    id: "petra",
    name: "Petra, Jordan",
    lat: 30.329, lng: 35.444,
    hint: "Middle East — rose-red city carved directly into sandstone cliffs",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Treasury_petra_crop.jpg/1280px-Treasury_petra_crop.jpg",
  },
  {
    id: "halong",
    name: "Ha Long Bay, Vietnam",
    lat: 20.910, lng: 107.184,
    hint: "Southeast Asia — thousands of limestone karst islets in emerald water",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Halong_Bay.jpg/1280px-Halong_Bay.jpg",
  },
  {
    id: "cappadocia",
    name: "Cappadocia, Turkey",
    lat: 38.643, lng: 34.830,
    hint: "Central Anatolia — fairy chimney rock formations dotted with hot-air balloons",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cappadocia_Balloon.jpg/1280px-Cappadocia_Balloon.jpg",
  },
  {
    id: "pamukkale",
    name: "Pamukkale, Turkey",
    lat: 37.921, lng: 29.119,
    hint: "Turkey — terraced white mineral pools cascading down a hillside",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Pammukale.jpg/1280px-Pammukale.jpg",
  },
  {
    id: "mount_fuji",
    name: "Mount Fuji, Japan",
    lat: 35.361, lng: 138.727,
    hint: "East Asia — perfectly cone-shaped snow-capped volcano",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/080103_hakkai-san_fuji.jpg/1280px-080103_hakkai-san_fuji.jpg",
  },
  {
    id: "zhangjiajie",
    name: "Zhangjiajie, China",
    lat: 29.118, lng: 110.479,
    hint: "Central China — pillar-shaped sandstone mountains cloaked in mist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Zhangjiajie_National_Forest_Park_-_Zhangjiajie%2C_Hunan%2C_China.jpg/1280px-Zhangjiajie_National_Forest_Park_-_Zhangjiajie%2C_Hunan%2C_China.jpg",
  },

  // ── Africa ───────────────────────────────────────────────────────────────────
  {
    id: "pyramids",
    name: "Pyramids of Giza, Egypt",
    lat: 29.979, lng: 31.134,
    hint: "North Africa — ancient stone pyramids rising from desert sands",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1280px-Kheops-Pyramid.jpg",
  },
  {
    id: "safari",
    name: "Serengeti, Tanzania",
    lat: -2.333, lng: 34.833,
    hint: "East Africa — vast grassland famous for the great migration",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Giraffe_in_Serengeti.jpg/1280px-Giraffe_in_Serengeti.jpg",
  },
  {
    id: "capetown",
    name: "Cape Town, South Africa",
    lat: -33.926, lng: 18.424,
    hint: "Southern Africa — city beneath a famous flat-topped mountain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Cape_Town_from_Table_Mountain.jpg/1280px-Cape_Town_from_Table_Mountain.jpg",
  },
  {
    id: "marrakech",
    name: "Marrakech, Morocco",
    lat: 31.629, lng: -7.981,
    hint: "North Africa — vibrant market city with red walls and labyrinthine souks",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Marrakesh_Djemaa_el_Fna_Square_panorama.jpg/1280px-Marrakesh_Djemaa_el_Fna_Square_panorama.jpg",
  },
  {
    id: "victoria_falls",
    name: "Victoria Falls, Zimbabwe",
    lat: -17.925, lng: 25.857,
    hint: "Southern Africa — the world's largest waterfall by total area",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Victoriaf%C3%A4llen.jpg/1280px-Victoriaf%C3%A4llen.jpg",
  },

  // ── Oceania ──────────────────────────────────────────────────────────────────
  {
    id: "sydney",
    name: "Sydney Opera House",
    lat: -33.857, lng: 151.215,
    hint: "Oceania — iconic shell-shaped performing arts venue on a harbour",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sydney_NSW_2000%2C_Australia_-_panoramio%2815%29.jpg/1280px-Sydney_NSW_2000%2C_Australia_-_panoramio%2815%29.jpg",
  },
  {
    id: "uluru",
    name: "Uluru, Australia",
    lat: -25.344, lng: 131.036,
    hint: "Oceania — massive ancient sandstone monolith in the Red Centre",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Uluru_monolith.jpg/1280px-Uluru_monolith.jpg",
  },
  {
    id: "newzealand",
    name: "Milford Sound, New Zealand",
    lat: -44.641, lng: 167.900,
    hint: "Oceania — dramatic fjord with waterfalls and mirror-flat water",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/MilfordSound.jpg/1280px-MilfordSound.jpg",
  },
  {
    id: "galapagos",
    name: "Galapagos Islands, Ecuador",
    lat: -0.966, lng: -90.961,
    hint: "South Pacific — remote volcanic islands with unique wildlife",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Galapagos_IslandsHI.jpg/1280px-Galapagos_IslandsHI.jpg",
  },

  // ── Wildcards ─────────────────────────────────────────────────────────────────
  {
    id: "reykjavik",
    name: "Reykjavik, Iceland",
    lat: 64.128, lng: -21.827,
    hint: "North Atlantic — colourful capital city with geothermal pools and aurora skies",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Reykjav%C3%ADk_old_town_2017.jpg/1280px-Reykjav%C3%ADk_old_town_2017.jpg",
  },
  {
    id: "iceland",
    name: "Northern Lights, Iceland",
    lat: 64.963, lng: -19.021,
    hint: "North Atlantic — swirling green curtains of light over a snowy landscape",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Northern_Lights_above_the_Öxará_river.jpg/1280px-Northern_Lights_above_the_%C3%96x%C3%A1r%C3%A1_river.jpg",
  },
  {
    id: "maldives",
    name: "Maldives",
    lat: 3.202, lng: 73.221,
    hint: "Indian Ocean — low-lying coral atolls with crystal-clear lagoons",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Maldives_Aerial_-_Bodufinolhu.jpg/1280px-Maldives_Aerial_-_Bodufinolhu.jpg",
  },
  {
    id: "alaska",
    name: "Denali, Alaska",
    lat: 63.069, lng: -151.007,
    hint: "North America — highest peak on the continent, surrounded by wilderness",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Denali_Mt_McKinley.jpg/1280px-Denali_Mt_McKinley.jpg",
  },
  {
    id: "antarctica",
    name: "Antarctica",
    lat: -82.863, lng: -135.000,
    hint: "Very cold — the southernmost continent, frozen and almost uninhabited",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Antarctica_sunset.jpg/1280px-Antarctica_sunset.jpg",
  },

  // ── Battle Sites & Historical ─────────────────────────────────────────────
  {
    id: "normandy",
    name: "Normandy Beaches, France",
    lat: 49.363, lng: -0.863,
    hint: "Northwestern France — wide flat beaches where one of history's largest seaborne invasions took place",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Normandy_American_Cemetery_and_Memorial.jpg/1280px-Normandy_American_Cemetery_and_Memorial.jpg",
  },
  {
    id: "waterloo",
    name: "Waterloo, Belgium",
    lat: 50.680, lng: 4.413,
    hint: "Central Belgium — rolling farmland that decided the fate of a French emperor in 1815",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Lion%27s_mound%2C_Belgium.jpg/1280px-Lion%27s_mound%2C_Belgium.jpg",
  },
  {
    id: "gettysburg",
    name: "Gettysburg, Pennsylvania",
    lat: 39.812, lng: -77.233,
    hint: "Eastern USA — quiet rolling hills that saw the bloodiest battle of the American Civil War",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Soldiers_National_Monument_Gettysburg.jpg/1280px-Soldiers_National_Monument_Gettysburg.jpg",
  },
  {
    id: "thermopylae",
    name: "Thermopylae, Greece",
    lat: 38.800, lng: 22.533,
    hint: "Central Greece — narrow coastal pass where 300 Spartans held an entire army",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Thermopylae_monument.jpg/1280px-Thermopylae_monument.jpg",
  },
  {
    id: "verdun",
    name: "Verdun, France",
    lat: 49.162, lng: 5.382,
    hint: "Northeastern France — cratered landscape from one of WWI's longest and deadliest battles",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Fort_Douaumont_2007.jpg/1280px-Fort_Douaumont_2007.jpg",
  },
  {
    id: "gallipoli",
    name: "Gallipoli, Turkey",
    lat: 40.143, lng: 26.397,
    hint: "Northwestern Turkey — rugged peninsula where ANZAC forces fought in WWI",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/ANZAC_Cove_Gallipoli.jpg/1280px-ANZAC_Cove_Gallipoli.jpg",
  },
  {
    id: "troy",
    name: "Troy (Hisarlik), Turkey",
    lat: 39.957, lng: 26.239,
    hint: "Western Turkey — archaeological site of the legendary ancient city immortalised in Homer's Iliad",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Trojan_horse_Canakkale.jpg/1280px-Trojan_horse_Canakkale.jpg",
  },
  {
    id: "pompeii",
    name: "Pompeii, Italy",
    lat: 40.749, lng: 14.486,
    hint: "Southern Italy — ancient Roman city frozen in time by a volcanic eruption in 79 AD",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Pompeii-street.jpg/1280px-Pompeii-street.jpg",
  },
  {
    id: "hastings",
    name: "Battle of Hastings, England",
    lat: 50.910, lng: 0.490,
    hint: "Southeast England — abbey ruins mark the field where 1066 changed English history forever",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Battle_Abbey_ruins.jpg/1280px-Battle_Abbey_ruins.jpg",
  },
  {
    id: "volgograd",
    name: "Volgograd (Stalingrad), Russia",
    lat: 48.707, lng: 44.517,
    hint: "Southern Russia — city on the Volga River site of the decisive WWII Eastern Front battle",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rodina-Mat%27_Zowjot.jpg/1280px-Rodina-Mat%27_Zowjot.jpg",
  },

  // ── Ancient & Lost Cities ─────────────────────────────────────────────────
  {
    id: "istanbul",
    name: "Hagia Sophia, Istanbul",
    lat: 41.009, lng: 28.980,
    hint: "Northwest Turkey — ancient domed basilica that has been church, mosque, and museum",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Hagia_Sophia_Istanbul_2014_1418.jpg/1280px-Hagia_Sophia_Istanbul_2014_1418.jpg",
  },
  {
    id: "persepolis",
    name: "Persepolis, Iran",
    lat: 29.934, lng: 52.891,
    hint: "Southern Iran — ceremonial capital of the ancient Persian Empire, now dramatic stone ruins",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/IranShirazPersepolis.jpg/1280px-IranShirazPersepolis.jpg",
  },
  {
    id: "tikal",
    name: "Tikal, Guatemala",
    lat: 17.222, lng: -89.623,
    hint: "Northern Guatemala — towering Maya temples rising above a dense jungle canopy",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Tikal_temple1_2006_08_11.jpg/1280px-Tikal_temple1_2006_08_11.jpg",
  },
  {
    id: "carthage",
    name: "Carthage, Tunisia",
    lat: 36.853, lng: 10.323,
    hint: "North Africa — ruins of the great Phoenician city that rivalled Rome, overlooking the Mediterranean",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Carthage_Roman_theatre.jpg/1280px-Carthage_Roman_theatre.jpg",
  },
  {
    id: "efes",
    name: "Ephesus, Turkey",
    lat: 37.939, lng: 27.341,
    hint: "Western Turkey — marble-paved streets and library ruins of one of the ancient world's greatest cities",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Efes_Celsus_Library_facade.jpg/1280px-Efes_Celsus_Library_facade.jpg",
  },
  {
    id: "mesa_verde",
    name: "Mesa Verde, Colorado",
    lat: 37.185, lng: -108.490,
    hint: "Southwest USA — cliff dwellings built into canyon walls by the ancient Ancestral Puebloan people",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Mesa_verde_national_park_cliff_palace_2006_09_12_by_Michael_Gäbler.jpg/1280px-Mesa_verde_national_park_cliff_palace_2006_09_12_by_Michael_Gäbler.jpg",
  },

  // ── Famous Concert & Music Venues ─────────────────────────────────────────
  {
    id: "red_rocks",
    name: "Red Rocks Amphitheatre, Colorado",
    lat: 39.665, lng: -105.205,
    hint: "Colorado, USA — natural outdoor amphitheatre carved between enormous red sandstone formations",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Red_Rocks_Amphitheatre_2011.jpg/1280px-Red_Rocks_Amphitheatre_2011.jpg",
  },
  {
    id: "glastonbury",
    name: "Glastonbury Festival, England",
    lat: 51.144, lng: -2.590,
    hint: "Somerset, England — muddy fields that host the world's most famous music festival every summer",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Glastonbury_Pyramid_Stage.jpg/1280px-Glastonbury_Pyramid_Stage.jpg",
  },
  {
    id: "royal_albert",
    name: "Royal Albert Hall, London",
    lat: 51.501, lng: -0.177,
    hint: "Central London — grand Victorian concert hall with an unmistakable circular red-brick form",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Royal_Albert_Hall_exterior%2C_2006.jpg/1280px-Royal_Albert_Hall_exterior%2C_2006.jpg",
  },
  {
    id: "coachella",
    name: "Coachella Valley, California",
    lat: 33.682, lng: -116.238,
    hint: "California desert — open-air festival grounds surrounded by date palms and mountain backdrops",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Coachella_2012_-_Main_Stage_%287114576763%29.jpg/1280px-Coachella_2012_-_Main_Stage_%287114576763%29.jpg",
  },
  {
    id: "wembley",
    name: "Wembley Stadium, London",
    lat: 51.556, lng: -0.280,
    hint: "North London — iconic arch-topped stadium that has hosted Live Aid, FA Cup finals and global superstars",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Wembley_Stadium_interior_Oct_2007.jpg/1280px-Wembley_Stadium_interior_Oct_2007.jpg",
  },
  {
    id: "hollywood_bowl",
    name: "Hollywood Bowl, Los Angeles",
    lat: 34.112, lng: -118.339,
    hint: "Los Angeles hills — classic bandshell amphitheatre where summer concerts have played since 1922",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Hollywood_bowl_2011_04_09.jpg/1280px-Hollywood_bowl_2011_04_09.jpg",
  },

  // ── Iconic Cities & Skylines ──────────────────────────────────────────────
  {
    id: "venice",
    name: "Venice, Italy",
    lat: 45.434, lng: 12.338,
    hint: "Northeastern Italy — canal city built on 118 small islands, no cars allowed",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Canale_Grande_Venezia.jpg/1280px-Canale_Grande_Venezia.jpg",
  },
  {
    id: "prague",
    name: "Prague, Czech Republic",
    lat: 50.087, lng: 14.421,
    hint: "Central Europe — medieval old town with an astronomical clock and castle on a hill",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Prague_-_Hradčany_castle_seen_from_Malá_Strana.jpg/1280px-Prague_-_Hradčany_castle_seen_from_Malá_Strana.jpg",
  },
  {
    id: "edinburgh",
    name: "Edinburgh Castle, Scotland",
    lat: 55.949, lng: -3.200,
    hint: "Scotland — fortress on an ancient volcanic rock overlooking a historic capital city",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Edinburgh_Castle_esplanade.jpg/1280px-Edinburgh_Castle_esplanade.jpg",
  },
  {
    id: "lisbon",
    name: "Lisbon, Portugal",
    lat: 38.722, lng: -9.139,
    hint: "Western Europe — pastel-coloured hillside city with yellow trams and Atlantic Ocean views",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/ViewTowards_SetubalPeninsula.jpg/1280px-ViewTowards_SetubalPeninsula.jpg",
  },
  {
    id: "rio_carnival",
    name: "Rio Carnival, Brazil",
    lat: -22.906, lng: -43.173,
    hint: "Rio de Janeiro — streets transformed for the world's largest carnival celebration each February",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/RioCarnival_2012.jpg/1280px-RioCarnival_2012.jpg",
  },
  {
    id: "hong_kong",
    name: "Hong Kong Skyline",
    lat: 22.319, lng: 114.169,
    hint: "East Asia — dense neon skyline of skyscrapers packed onto a mountainous harbour island",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Hong_Kong_Night_Skyline.jpg/1280px-Hong_Kong_Night_Skyline.jpg",
  },
  {
    id: "new_orleans",
    name: "New Orleans, Louisiana",
    lat: 29.960, lng: -90.062,
    hint: "Southern USA — jazz-soaked French Quarter with iron-lacework balconies and Mardi Gras beads",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/New_Orleans_-_Bourbon_Street.jpg/1280px-New_Orleans_-_Bourbon_Street.jpg",
  },
  {
    id: "buenos_aires",
    name: "Buenos Aires, Argentina",
    lat: -34.604, lng: -58.381,
    hint: "South America — Paris of the south, wide boulevards and European-style architecture",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Buenos_Aires_-_Obelisco.jpg/1280px-Buenos_Aires_-_Obelisco.jpg",
  },
  {
    id: "nairobi",
    name: "Nairobi, Kenya",
    lat: -1.292, lng: 36.821,
    hint: "East Africa — modern city skyline where giraffe can sometimes be seen from the suburbs",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Nairobi_City_Skyline.jpg/1280px-Nairobi_City_Skyline.jpg",
  },
  {
    id: "mumbai",
    name: "Mumbai, India",
    lat: 18.922, lng: 72.834,
    hint: "Western India — colonial Gateway arch on the waterfront of India's most populous city",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/1280px-Mumbai_03-2016_30_Gateway_of_India.jpg",
  },
  {
    id: "seoul",
    name: "Seoul, South Korea",
    lat: 37.566, lng: 126.978,
    hint: "East Asia — ancient palaces surrounded by one of the world's most wired modern cities",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Gyeongbokgung-oct-2019.jpg/1280px-Gyeongbokgung-oct-2019.jpg",
  },
  {
    id: "istanbul_bridge",
    name: "Bosphorus Bridge, Istanbul",
    lat: 41.045, lng: 29.034,
    hint: "Turkey — bridge straddling the only strait where two continents meet",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Bosphorus_Bridge_1.jpg/1280px-Bosphorus_Bridge_1.jpg",
  },

  // ── Nature & Landscape ────────────────────────────────────────────────────
  {
    id: "sahara",
    name: "Sahara Desert, Algeria",
    lat: 23.416, lng: 5.361,
    hint: "North Africa — endless rolling orange dunes, the world's largest hot desert",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Sahara_des_dunes.jpg/1280px-Sahara_des_dunes.jpg",
  },
  {
    id: "amazon",
    name: "Amazon Rainforest, Brazil",
    lat: -3.467, lng: -62.217,
    hint: "South America — vast green lung of the planet, home to more species than anywhere on Earth",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Casiquiare_channel_from_above.jpg/1280px-Casiquiare_channel_from_above.jpg",
  },
  {
    id: "great_barrier",
    name: "Great Barrier Reef, Australia",
    lat: -18.286, lng: 147.700,
    hint: "Queensland, Australia — the world's largest coral reef system, visible from space",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Great_Barrier_Reef_2010.jpg/1280px-Great_Barrier_Reef_2010.jpg",
  },
  {
    id: "grand_prismatic",
    name: "Grand Prismatic Spring, Wyoming",
    lat: 44.525, lng: -110.838,
    hint: "Yellowstone, USA — the world's third largest hot spring, ringed in vivid rainbow colours",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Grand_prismatic_spring.jpg/1280px-Grand_prismatic_spring.jpg",
  },
  {
    id: "fjords",
    name: "Sognefjord, Norway",
    lat: 61.212, lng: 6.881,
    hint: "Western Norway — the world's longest fjord, surrounded by steep mountains and waterfalls",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Sognefjorden.jpg/1280px-Sognefjorden.jpg",
  },
  {
    id: "mount_everest",
    name: "Mount Everest Base Camp, Nepal",
    lat: 28.002, lng: 86.856,
    hint: "Himalayas — the camp at the foot of the world's highest mountain, at 5,364 metres",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg/1280px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg",
  },
  {
    id: "dead_sea",
    name: "Dead Sea, Jordan/Israel",
    lat: 31.559, lng: 35.473,
    hint: "Middle East — the saltiest large body of water on Earth, the lowest point on land",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Dead_Sea_Jordan_by_David_Shankbone.jpg/1280px-Dead_Sea_Jordan_by_David_Shankbone.jpg",
  },
  {
    id: "atacama",
    name: "Atacama Desert, Chile",
    lat: -24.500, lng: -69.250,
    hint: "Northern Chile — the driest non-polar desert on Earth, with salt flats and geysers",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Atacama_salt_flat.jpg/1280px-Atacama_salt_flat.jpg",
  },
  {
    id: "aoraki",
    name: "Aoraki / Mount Cook, New Zealand",
    lat: -43.595, lng: 170.141,
    hint: "South Island, New Zealand — tallest peak in the country, filmed as Middle-earth",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Aoraki_Mount_Cook_-_Luca_Galuzzi_2005.jpg/1280px-Aoraki_Mount_Cook_-_Luca_Galuzzi_2005.jpg",
  },

  // ── UK & Local Landmarks ──────────────────────────────────────────────────
  {
    id: "tower_bridge",
    name: "Tower Bridge, London",
    lat: 51.506, lng: -0.076,
    hint: "East London — Victorian bascule bridge with distinctive Gothic towers over the Thames",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Tower_bridge_London_Flickr.jpg/1280px-Tower_bridge_London_Flickr.jpg",
  },
  {
    id: "lake_district",
    name: "Lake District, England",
    lat: 54.461, lng: -3.084,
    hint: "Northwest England — misty fells, glacial lakes and stone walls in England's largest national park",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Windermere_from_the_south.jpg/1280px-Windermere_from_the_south.jpg",
  },
  {
    id: "giants_causeway",
    name: "Giant's Causeway, Northern Ireland",
    lat: 55.241, lng: -6.512,
    hint: "Northern Ireland — tens of thousands of interlocking basalt columns formed by ancient volcanic activity",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Causeway-code_poet-4.jpg/1280px-Causeway-code_poet-4.jpg",
  },
  {
    id: "cliffs_of_moher",
    name: "Cliffs of Moher, Ireland",
    lat: 52.972, lng: -9.426,
    hint: "Western Ireland — dramatic 200-metre sea cliffs stretching along the Atlantic coast",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Cliffs_of_Moher_and_O%27Brien%27s_Tower.jpg/1280px-Cliffs_of_Moher_and_O%27Brien%27s_Tower.jpg",
  },
  {
    id: "bath",
    name: "Roman Baths, Bath",
    lat: 51.382, lng: -2.360,
    hint: "Southwest England — perfectly preserved ancient Roman bathing complex still steaming today",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Roman_Baths_in_Bath_Spa%2C_England_-_July_2006.jpg/1280px-Roman_Baths_in_Bath_Spa%2C_England_-_July_2006.jpg",
  },
];
