export interface GeoLocation {
  id: string;
  name: string;       // Revealed AFTER guessing
  lat: number;
  lng: number;
  hint: string;       // Vague clue shown during guessing (continent / climate)
  imageUrl?: string;  // Real Wikimedia Commons image URL
}

export const GEO_LOCATIONS: GeoLocation[] = [
  // ── Europe ──────────────────────────────────────────────────────────────────
  {
    id: "paris",
    name: "Eiffel Tower, Paris",
    lat: 48.858, lng: 2.295,
    hint: "Western Europe — iron lattice tower dominates the skyline",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg/1280px-Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg",
  },
  {
    id: "rome",
    name: "Colosseum, Rome",
    lat: 41.890, lng: 12.492,
    hint: "Southern Europe — ancient stone amphitheatre",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Colosseo_2020.jpg/1280px-Colosseo_2020.jpg",
  },
  {
    id: "london",
    name: "Big Ben, London",
    lat: 51.501, lng: -0.124,
    hint: "Northern Europe — famous clock tower beside a river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007_icon.png/800px-Clock_Tower_-_Palace_of_Westminster%2C_London_-_May_2007_icon.png",
  },
  {
    id: "barcelona",
    name: "Sagrada Família, Barcelona",
    lat: 41.404, lng: 2.174,
    hint: "Southern Europe — unfinished cathedral with organic spires",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Sagrada_Familia_nave_roof_detail.jpg/1280px-Sagrada_Familia_nave_roof_detail.jpg",
  },
  {
    id: "athens",
    name: "Acropolis, Athens",
    lat: 37.971, lng: 23.726,
    hint: "Southern Europe — ancient hilltop temple complex",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Parthenon_in_Athens.jpg/1280px-The_Parthenon_in_Athens.jpg",
  },
  {
    id: "amsterdam",
    name: "Canals, Amsterdam",
    lat: 52.374, lng: 4.890,
    hint: "Western Europe — city of historic waterways and narrow houses",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Amsterdam_-_Wikimedia_Commons_%281%29.jpg/1280px-Amsterdam_-_Wikimedia_Commons_%281%29.jpg",
  },
  {
    id: "santorini",
    name: "Santorini, Greece",
    lat: 36.393, lng: 25.461,
    hint: "Mediterranean — white cube buildings on a volcanic caldera",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Santorini_-_panoramio_%283%29.jpg/1280px-Santorini_-_panoramio_%283%29.jpg",
  },
  {
    id: "stonehenge",
    name: "Stonehenge, England",
    lat: 51.179, lng: -1.826,
    hint: "Northwestern Europe — prehistoric stone circle on a grassy plain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Stonehenge2007_07_30.jpg/1280px-Stonehenge2007_07_30.jpg",
  },
  {
    id: "budapest",
    name: "Budapest, Hungary",
    lat: 47.498, lng: 19.040,
    hint: "Central Europe — parliament building straddling a great river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Parliament_Budapest_2010.jpg/1280px-Parliament_Budapest_2010.jpg",
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik, Croatia",
    lat: 42.651, lng: 18.094,
    hint: "Adriatic coast — walled medieval city by a turquoise sea",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Dubrovnik_-_Old_City_Walls.jpg/1280px-Dubrovnik_-_Old_City_Walls.jpg",
  },
  {
    id: "amalfi",
    name: "Amalfi Coast, Italy",
    lat: 40.634, lng: 14.603,
    hint: "Southern Italy — colourful cliffside villages above a blue sea",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Costiera_amalfitana.jpg/1280px-Costiera_amalfitana.jpg",
  },

  // ── Americas ─────────────────────────────────────────────────────────────────
  {
    id: "nyc",
    name: "Statue of Liberty, New York",
    lat: 40.689, lng: -74.044,
    hint: "North America — copper lady on an island in a famous harbour",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/24701-nature-natural-beauty.jpg/1280px-24701-nature-natural-beauty.jpg",
  },
  {
    id: "rio",
    name: "Christ the Redeemer, Rio",
    lat: -22.952, lng: -43.210,
    hint: "South America — giant statue with arms wide open on a mountain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Christ_the_Redeemer_-_Cristo_Redentor.jpg/1280px-Christ_the_Redeemer_-_Cristo_Redentor.jpg",
  },
  {
    id: "machu",
    name: "Machu Picchu, Peru",
    lat: -13.163, lng: -72.545,
    hint: "South America — Inca citadel hidden in the Andes cloud forest",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1280px-Machu_Picchu%2C_Peru.jpg",
  },
  {
    id: "chicago",
    name: "Chicago, USA",
    lat: 41.878, lng: -87.630,
    hint: "North America — windy city with distinctive bean sculpture",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Chicago_lakefront_skyline_c2009-2.jpg/1280px-Chicago_lakefront_skyline_c2009-2.jpg",
  },
  {
    id: "mexico",
    name: "Chichen Itza, Mexico",
    lat: 20.683, lng: -88.569,
    hint: "Central America — stepped Maya pyramid in the jungle",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/1280px-Chichen_Itza_3.jpg",
  },
  {
    id: "patagonia",
    name: "Patagonia, Argentina",
    lat: -51.629, lng: -72.700,
    hint: "Southern South America — dramatic granite towers above glaciers",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Patagonia_-_Argentina_%28cropped%29.jpg/1280px-Patagonia_-_Argentina_%28cropped%29.jpg",
  },
  {
    id: "havana",
    name: "Havana, Cuba",
    lat: 23.135, lng: -82.359,
    hint: "Caribbean — colourful colonial streets with vintage American cars",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Havana-streets2.jpg/1280px-Havana-streets2.jpg",
  },
  {
    id: "grand_canyon",
    name: "Grand Canyon, USA",
    lat: 36.106, lng: -112.113,
    hint: "North America — massive rust-red gorge carved by a river",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg/1280px-USA_09847_Grand_Canyon_Luca_Galuzzi_2007.jpg",
  },
  {
    id: "banff",
    name: "Banff, Canada",
    lat: 51.178, lng: -115.571,
    hint: "North America — turquoise glacial lake framed by Rocky Mountains",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Moraine_Lake_17092005.jpg/1280px-Moraine_Lake_17092005.jpg",
  },
  {
    id: "iguazu",
    name: "Iguazu Falls, Argentina",
    lat: -25.695, lng: -54.437,
    hint: "South America — vast waterfall system wider than Niagara",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Iguazu_Argentina_Luca_Galuzzi_2007_03.jpg/1280px-Iguazu_Argentina_Luca_Galuzzi_2007_03.jpg",
  },
  {
    id: "easter_island",
    name: "Easter Island, Chile",
    lat: -27.112, lng: -109.349,
    hint: "South Pacific — mysterious giant stone heads on a remote island",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Easter_Island_Ahu_Tongariki.jpg/1280px-Easter_Island_Ahu_Tongariki.jpg",
  },

  // ── Asia ─────────────────────────────────────────────────────────────────────
  {
    id: "taj",
    name: "Taj Mahal, India",
    lat: 27.175, lng: 78.042,
    hint: "South Asia — white marble mausoleum reflected in a long pool",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/1280px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg",
  },
  {
    id: "tokyo",
    name: "Tokyo, Japan",
    lat: 35.689, lng: 139.692,
    hint: "East Asia — futuristic megacity with neon-lit crossings",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg",
  },
  {
    id: "china",
    name: "Great Wall, China",
    lat: 40.432, lng: 116.570,
    hint: "East Asia — ancient stone wall winding over mountain ridges",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/1280px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg",
  },
  {
    id: "dubai",
    name: "Burj Khalifa, Dubai",
    lat: 25.197, lng: 55.274,
    hint: "Middle East — world's tallest skyscraper in a desert city",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Burj_Khalifa.jpg/800px-Burj_Khalifa.jpg",
  },
  {
    id: "angkor",
    name: "Angkor Wat, Cambodia",
    lat: 13.412, lng: 103.867,
    hint: "Southeast Asia — vast Hindu-Buddhist temple complex in the jungle",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Angkor_Wat_temple.jpg/1280px-Angkor_Wat_temple.jpg",
  },
  {
    id: "singapore",
    name: "Marina Bay, Singapore",
    lat: 1.282, lng: 103.861,
    hint: "Southeast Asia — futuristic skyline with a rooftop infinity pool",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Singapura_-_Skyline_nocturno_%28by_Drriss_%26_Marrionn%29.jpg/1280px-Singapura_-_Skyline_nocturno_%28by_Drriss_%26_Marrionn%29.jpg",
  },
  {
    id: "kyoto",
    name: "Fushimi Inari, Kyoto",
    lat: 34.967, lng: 135.773,
    hint: "East Asia — thousands of bright orange torii gates up a forested hill",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Fushimi_inari_taisha_1.jpg/1280px-Fushimi_inari_taisha_1.jpg",
  },
  {
    id: "bali",
    name: "Bali, Indonesia",
    lat: -8.340, lng: 115.092,
    hint: "Southeast Asia — terraced rice paddies and ornate Hindu temples",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Bali_Indonesia_%28241279698%29.jpg/1280px-Bali_Indonesia_%28241279698%29.jpg",
  },
  {
    id: "petra",
    name: "Petra, Jordan",
    lat: 30.329, lng: 35.444,
    hint: "Middle East — rose-red city carved directly into sandstone cliffs",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Treasury_petra_crop.jpg/1280px-Treasury_petra_crop.jpg",
  },
  {
    id: "halong",
    name: "Ha Long Bay, Vietnam",
    lat: 20.910, lng: 107.184,
    hint: "Southeast Asia — thousands of limestone karst islets in emerald water",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Halong_Bay.jpg/1280px-Halong_Bay.jpg",
  },
  {
    id: "cappadocia",
    name: "Cappadocia, Turkey",
    lat: 38.643, lng: 34.830,
    hint: "Central Anatolia — fairy chimney rock formations dotted with hot-air balloons",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Cappadocia_Balloon.jpg/1280px-Cappadocia_Balloon.jpg",
  },
  {
    id: "pamukkale",
    name: "Pamukkale, Turkey",
    lat: 37.921, lng: 29.119,
    hint: "Turkey — terraced white mineral pools cascading down a hillside",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Pammukale.jpg/1280px-Pammukale.jpg",
  },
  {
    id: "mount_fuji",
    name: "Mount Fuji, Japan",
    lat: 35.361, lng: 138.727,
    hint: "East Asia — perfectly cone-shaped snow-capped volcano",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/080103_hakkai-san_fuji.jpg/1280px-080103_hakkai-san_fuji.jpg",
  },
  {
    id: "zhangjiajie",
    name: "Zhangjiajie, China",
    lat: 29.118, lng: 110.479,
    hint: "Central China — pillar-shaped sandstone mountains cloaked in mist",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Zhangjiajie_National_Forest_Park_-_Zhangjiajie%2C_Hunan%2C_China.jpg/1280px-Zhangjiajie_National_Forest_Park_-_Zhangjiajie%2C_Hunan%2C_China.jpg",
  },

  // ── Africa ───────────────────────────────────────────────────────────────────
  {
    id: "pyramids",
    name: "Pyramids of Giza, Egypt",
    lat: 29.979, lng: 31.134,
    hint: "North Africa — ancient stone pyramids rising from desert sands",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1280px-Kheops-Pyramid.jpg",
  },
  {
    id: "safari",
    name: "Serengeti, Tanzania",
    lat: -2.333, lng: 34.833,
    hint: "East Africa — vast grassland famous for the great migration",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Giraffe_in_Serengeti.jpg/1280px-Giraffe_in_Serengeti.jpg",
  },
  {
    id: "capetown",
    name: "Cape Town, South Africa",
    lat: -33.926, lng: 18.424,
    hint: "Southern Africa — city beneath a famous flat-topped mountain",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Cape_Town_from_Table_Mountain.jpg/1280px-Cape_Town_from_Table_Mountain.jpg",
  },
  {
    id: "marrakech",
    name: "Marrakech, Morocco",
    lat: 31.629, lng: -7.981,
    hint: "North Africa — vibrant market city with red walls and labyrinthine souks",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Marrakesh_Djemaa_el_Fna_Square_panorama.jpg/1280px-Marrakesh_Djemaa_el_Fna_Square_panorama.jpg",
  },
  {
    id: "victoria_falls",
    name: "Victoria Falls, Zimbabwe",
    lat: -17.925, lng: 25.857,
    hint: "Southern Africa — the world's largest waterfall by total area",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Victoriaf%C3%A4llen.jpg/1280px-Victoriaf%C3%A4llen.jpg",
  },

  // ── Oceania ──────────────────────────────────────────────────────────────────
  {
    id: "sydney",
    name: "Sydney Opera House",
    lat: -33.857, lng: 151.215,
    hint: "Oceania — iconic shell-shaped performing arts venue on a harbour",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Sydney_NSW_2000%2C_Australia_-_panoramio%2815%29.jpg/1280px-Sydney_NSW_2000%2C_Australia_-_panoramio%2815%29.jpg",
  },
  {
    id: "uluru",
    name: "Uluru, Australia",
    lat: -25.344, lng: 131.036,
    hint: "Oceania — massive ancient sandstone monolith in the Red Centre",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Uluru_monolith.jpg/1280px-Uluru_monolith.jpg",
  },
  {
    id: "newzealand",
    name: "Milford Sound, New Zealand",
    lat: -44.641, lng: 167.900,
    hint: "Oceania — dramatic fjord with waterfalls and mirror-flat water",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/MilfordSound.jpg/1280px-MilfordSound.jpg",
  },
  {
    id: "galapagos",
    name: "Galapagos Islands, Ecuador",
    lat: -0.966, lng: -90.961,
    hint: "South Pacific — remote volcanic islands with unique wildlife",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Galapagos_IslandsHI.jpg/1280px-Galapagos_IslandsHI.jpg",
  },

  // ── Wildcards ─────────────────────────────────────────────────────────────────
  {
    id: "reykjavik",
    name: "Reykjavik, Iceland",
    lat: 64.128, lng: -21.827,
    hint: "North Atlantic — colourful capital city with geothermal pools and aurora skies",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Reykjav%C3%ADk_old_town_2017.jpg/1280px-Reykjav%C3%ADk_old_town_2017.jpg",
  },
  {
    id: "iceland",
    name: "Northern Lights, Iceland",
    lat: 64.963, lng: -19.021,
    hint: "North Atlantic — swirling green curtains of light over a snowy landscape",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Northern_Lights_above_the_Öxará_river.jpg/1280px-Northern_Lights_above_the_%C3%96x%C3%A1r%C3%A1_river.jpg",
  },
  {
    id: "maldives",
    name: "Maldives",
    lat: 3.202, lng: 73.221,
    hint: "Indian Ocean — low-lying coral atolls with crystal-clear lagoons",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Maldives_Aerial_-_Bodufinolhu.jpg/1280px-Maldives_Aerial_-_Bodufinolhu.jpg",
  },
  {
    id: "alaska",
    name: "Denali, Alaska",
    lat: 63.069, lng: -151.007,
    hint: "North America — highest peak on the continent, surrounded by wilderness",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Denali_Mt_McKinley.jpg/1280px-Denali_Mt_McKinley.jpg",
  },
  {
    id: "antarctica",
    name: "Antarctica",
    lat: -82.863, lng: -135.000,
    hint: "Very cold — the southernmost continent, frozen and almost uninhabited",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Antarctica_sunset.jpg/1280px-Antarctica_sunset.jpg",
  },
];
